ALTER TABLE TESTE.TB_TESTE_UF DROP PRIMARY KEY CASCADE;

DROP TABLE TESTE.TB_TESTE_UF CASCADE CONSTRAINTS;

CREATE TABLE TESTE.TB_TESTE_UF
(
  COD_UF         NUMBER                     NOT NULL,
  NOME        VARCHAR2(2 BYTE)               NOT NULL,
  NOME_COMPLETO  VARCHAR2(50 BYTE)              NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TESTE.TB_TESTE_UF_PK ON TESTE.TB_TESTE_UF
(COD_UF)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TESTE.TB_TESTE_UF_U01 ON TESTE.TB_TESTE_UF
(NOME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TESTE.TB_TESTE_UF ADD (
  CONSTRAINT TB_TESTE_UF_PK
 PRIMARY KEY
 (COD_UF)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT TB_TESTE_UF_U01
 UNIQUE (NOME)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


INSERT INTO TB_TESTE_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (1, 'MS', 'Mato Grosso do Sul');
INSERT INTO TB_TESTE_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (2, 'RS', 'Rio Grande do Sul');
INSERT INTO TB_TESTE_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (3, 'MT', 'Mato Grosso');
INSERT INTO TB_TESTE_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (4, 'SP', 'São Paulo');
COMMIT;





ALTER TABLE TESTE.TB_TESTE_CIDADES DROP PRIMARY KEY CASCADE;

DROP TABLE TESTE.TB_TESTE_CIDADES CASCADE CONSTRAINTS;

CREATE TABLE TESTE.TB_TESTE_CIDADES
(
  COD_CIDADE         NUMBER                     NOT NULL,
  COD_UF         NUMBER                     NOT NULL,
  NOME        VARCHAR2(20 BYTE)               NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TESTE.TB_TESTE_CIDADES_PK ON TESTE.TB_TESTE_CIDADES
(COD_CIDADE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TESTE.TB_TESTE_CIDADES_U01 ON TESTE.TB_TESTE_CIDADES
(NOME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TESTE.TB_TESTE_CIDADES ADD (
  CONSTRAINT TB_TESTE_CIDADES_PK
 PRIMARY KEY
 (COD_CIDADE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT TB_TESTE_CIDADES_U01
 UNIQUE (NOME)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


CREATE OR REPLACE PACKAGE TESTE."DML_TB_TESTE_PESSOAS" IS
    PROCEDURE INS_TB_TESTE_PESSOAS (
        out_COD_PESSOA OUT TESTE.TB_TESTE_PESSOAS.COD_PESSOA%TYPE,
        in_NOME IN TESTE.TB_TESTE_PESSOAS.NOME%TYPE,
        in_CPF IN TESTE.TB_TESTE_PESSOAS.CPF%TYPE,
        in_RG IN TESTE.TB_TESTE_PESSOAS.RG%TYPE,
        in_TELEFONE IN TESTE.TB_TESTE_PESSOAS.TELEFONE%TYPE,
        in_EMAIL IN TESTE.TB_TESTE_PESSOAS.EMAIL%TYPE,
        in_SEXO IN TESTE.TB_TESTE_PESSOAS.SEXO%TYPE,
        in_DATA_NASCIMENTO IN TESTE.TB_TESTE_PESSOAS.DATA_NASCIMENTO%TYPE
    );
END DML_TB_TESTE_PESSOAS;
/



CREATE OR REPLACE PACKAGE BODY TESTE."DML_TB_TESTE_PESSOAS"
IS
   PROCEDURE INS_TB_TESTE_PESSOAS (
        out_COD_PESSOA OUT TESTE.TB_TESTE_PESSOAS.COD_PESSOA%TYPE,
        in_NOME IN TESTE.TB_TESTE_PESSOAS.NOME%TYPE,
        in_CPF IN TESTE.TB_TESTE_PESSOAS.CPF%TYPE,
        in_RG IN TESTE.TB_TESTE_PESSOAS.RG%TYPE,
        in_TELEFONE IN TESTE.TB_TESTE_PESSOAS.TELEFONE%TYPE,
        in_EMAIL IN TESTE.TB_TESTE_PESSOAS.EMAIL%TYPE,
        in_SEXO IN TESTE.TB_TESTE_PESSOAS.SEXO%TYPE,
        in_DATA_NASCIMENTO IN TESTE.TB_TESTE_PESSOAS.DATA_NASCIMENTO%TYPE)
   IS
   BEGIN
      INSERT INTO TESTE.TB_TESTE_PESSOAS (NOME,
                                      CPF,
                                      RG,
                                      TELEFONE,
                                      EMAIL,
                                      SEXO,
                                      DATA_NASCIMENTO)
           VALUES (in_NOME,
                         in_CPF,
                         in_RG,
                         in_TELEFONE,
                         in_EMAIL,
                         in_SEXO,
                         in_DATA_NASCIMENTO)
        RETURNING COD_PESSOA
             INTO out_COD_PESSOA;
   END INS_TB_TESTE_PESSOAS;
END DML_TB_TESTE_PESSOAS;
/



INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (1, 1, 'Campo Grande');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (2, 1, 'Três Lagoas');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (3, 1, 'Bonito');

INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (4, 2, 'Porto Alegre');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (5, 2, 'Santa Maria');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (6, 2, 'Santo Ângelo');

INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (7, 3, 'Cuiabá');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (8, 3, 'Tangará da Serra');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (9, 3, 'Alta Floresta');

INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (10, 4, 'São Paulo');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (11, 4, 'Santo André');
INSERT INTO TB_TESTE_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (12, 4, 'Diadema');

COMMIT;


