ALTER TABLE DBAODB.TESTE_DEV_UF DROP PRIMARY KEY CASCADE;

DROP TABLE DBAODB.TESTE_DEV_UF CASCADE CONSTRAINTS;

CREATE TABLE DBAODB.TESTE_DEV_UF
(
  COD_UF         NUMBER                     NOT NULL,
  NOME        VARCHAR2(2 BYTE)               NOT NULL,
  NOME_COMPLETO  VARCHAR2(50 BYTE)              NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DBAODB.TESTE_DEV_UF_PK ON DBAODB.TESTE_DEV_UF
(COD_UF)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DBAODB.TESTE_DEV_UF_U01 ON DBAODB.TESTE_DEV_UF
(NOME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DBAODB.TESTE_DEV_UF ADD (
  CONSTRAINT TESTE_DEV_UF_PK
 PRIMARY KEY
 (COD_UF)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT TESTE_DEV_UF_U01
 UNIQUE (NOME)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


INSERT INTO TESTE_DEV_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (1, 'MS', 'Mato Grosso do Sul');
INSERT INTO TESTE_DEV_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (2, 'RS', 'Rio Grande do Sul');
INSERT INTO TESTE_DEV_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (3, 'MT', 'Mato Grosso');
INSERT INTO TESTE_DEV_UF (COD_UF, NOME, NOME_COMPLETO) VALUES (4, 'SP', 'São Paulo');
COMMIT;





ALTER TABLE DBAODB.TESTE_DEV_CIDADES DROP PRIMARY KEY CASCADE;

DROP TABLE DBAODB.TESTE_DEV_CIDADES CASCADE CONSTRAINTS;

CREATE TABLE DBAODB.TESTE_DEV_CIDADES
(
  COD_CIDADE         NUMBER                     NOT NULL,
  COD_UF         NUMBER                     NOT NULL,
  NOME        VARCHAR2(20 BYTE)               NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DBAODB.TESTE_DEV_CIDADES_PK ON DBAODB.TESTE_DEV_CIDADES
(COD_CIDADE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX DBAODB.TESTE_DEV_CIDADES_U01 ON DBAODB.TESTE_DEV_CIDADES
(NOME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DBAODB.TESTE_DEV_CIDADES ADD (
  CONSTRAINT TESTE_DEV_CIDADES_PK
 PRIMARY KEY
 (COD_CIDADE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT TESTE_DEV_CIDADES_U01
 UNIQUE (NOME)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


CREATE OR REPLACE PACKAGE DBAODB."DML_TESTE_DEV_PESSOAS" IS
    PROCEDURE INS_TESTE_DEV_PESSOAS (
        out_COD_PESSOA OUT DBAODB.TESTE_DEV_PESSOAS.COD_PESSOA%TYPE,
        in_NOME IN DBAODB.TESTE_DEV_PESSOAS.NOME%TYPE,
        in_CPF IN DBAODB.TESTE_DEV_PESSOAS.CPF%TYPE,
        in_RG IN DBAODB.TESTE_DEV_PESSOAS.RG%TYPE,
        in_TELEFONE IN DBAODB.TESTE_DEV_PESSOAS.TELEFONE%TYPE,
        in_EMAIL IN DBAODB.TESTE_DEV_PESSOAS.EMAIL%TYPE,
        in_SEXO IN DBAODB.TESTE_DEV_PESSOAS.SEXO%TYPE,
        in_DATA_NASCIMENTO IN DBAODB.TESTE_DEV_PESSOAS.DATA_NASCIMENTO%TYPE
    );
END DML_TESTE_DEV_PESSOAS;
/



CREATE OR REPLACE PACKAGE BODY DBAODB."DML_TESTE_DEV_PESSOAS"
IS
   PROCEDURE INS_TESTE_DEV_PESSOAS (
        out_COD_PESSOA OUT DBAODB.TESTE_DEV_PESSOAS.COD_PESSOA%TYPE,
        in_NOME IN DBAODB.TESTE_DEV_PESSOAS.NOME%TYPE,
        in_CPF IN DBAODB.TESTE_DEV_PESSOAS.CPF%TYPE,
        in_RG IN DBAODB.TESTE_DEV_PESSOAS.RG%TYPE,
        in_TELEFONE IN DBAODB.TESTE_DEV_PESSOAS.TELEFONE%TYPE,
        in_EMAIL IN DBAODB.TESTE_DEV_PESSOAS.EMAIL%TYPE,
        in_SEXO IN DBAODB.TESTE_DEV_PESSOAS.SEXO%TYPE,
        in_DATA_NASCIMENTO IN DBAODB.TESTE_DEV_PESSOAS.DATA_NASCIMENTO%TYPE)
   IS
   BEGIN
      INSERT INTO DBAODB.TESTE_DEV_PESSOAS (NOME,
                                      CPF,
                                      RG,
                                      TELEFONE,
                                      EMAIL,
                                      SEXO,
                                      DATA_NASCIMENTO)
           VALUES (in_NOME,
                         in_CPF,
                         in_RG,
                         in_TELEFONE,
                         in_EMAIL,
                         in_SEXO,
                         in_DATA_NASCIMENTO)
        RETURNING COD_PESSOA
             INTO out_COD_PESSOA;
   END INS_TESTE_DEV_PESSOAS;
END DML_TESTE_DEV_PESSOAS;
/



INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (1, 1, 'Campo Grande');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (2, 1, 'Três Lagoas');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (3, 1, 'Bonito');

INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (4, 2, 'Porto Alegre');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (5, 2, 'Santa Maria');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (6, 2, 'Santo Ângelo');

INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (7, 3, 'Cuiabá');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (8, 3, 'Tangará da Serra');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (9, 3, 'Alta Floresta');

INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (10, 4, 'São Paulo');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (11, 4, 'Santo André');
INSERT INTO DBAODB.TESTE_DEV_CIDADES (COD_CIDADE, COD_UF, NOME) VALUES (12, 4, 'Diadema');

COMMIT;


